name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies in virtual environment
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Code formatting check
        run: |
          source venv/bin/activate
          pip install black
          black --check .

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 .

      - name: Run tests with coverage
        run: |
          source venv/bin/activate
          pip install coverage pytest
          coverage run -m pytest
          coverage report -m

      - name: Run main
        run: |
          source venv/bin/activate
          python src/main.py
